---
mgmt_gateway: 192.168.111.1

custom_structured_configuration_ethernet_interfaces:
  Ethernet5/1:
    # speed: forced 10000full
    type: switched
    shutdown: false

custom_structured_configuration_vrfs:
  TENANT_A_WAN:
    ip_routing: true