CVP_CONFIGLETS: {}
CVP_TOPOLOGY:
  MPLS_FABRIC:
    parent_container: Tenant
  PE_ROUTERS:
    devices: []
    parent_container: MPLS_FABRIC
  RR_ROUTERS:
    devices: []
    parent_container: MPLS_FABRIC
changed: false
